export {default as Contacts} from './Contacts/Contacts.js'
export {default as Dishes} from './Dishes/Dishes.js'
export {default as Order} from './Order/Order.js'
export {default as Main} from './Main/Main.js'
export {default as Cart} from './Cart/Cart.js'
