export { default as Categories} from './Categories/Categories'
export { default as DishesButton} from './DishesButton/DishesButton'
export { default as DishesHeader} from './DishesHeader/DishesHeader'
export { default as Footer} from './Footer/Footer'
export { default as Header} from './Header/Header'