export { default as Categories} from './Categories/Categories'
export { default as DishesButton} from './DishesButton/DishesButton'
export { default as DishesHeader} from './DishesHeader/DishesHeader'
export { default as DishesSort} from './DishesSort/DishesSort.js'
export { default as DishesBlock} from './DishesBlock/DishesBlock.js'
export { default as DishesLoadingBlock} from './DishesBlock/DishesLoadingBlock.js'
export { default as CartItem} from './CartItem/CartItem.js'
export { default as Footer} from './Footer/Footer'
export { default as Header} from './Header/Header'
export { default as Navbar} from './Navbar/Navbar'
export { default as Logo} from './Logo/Logo'
export { default as HeaderContacts} from './HeaderContacts/HeaderContacts'


export { default as Title} from './Title/Title'