export { default as Categories} from './Categories/Categories'
export { default as DishesButton} from './DishesButton/DishesButton'
export { default as DishesHeader} from './DishesHeader/DishesHeader'
export { default as DishesSort} from './DishesSort/DishesSort.js'
export { default as DishesBlock} from './DishesBlock/DishesBlock.js'
export { default as Footer} from './Footer/Footer'
export { default as Header} from './Header/Header'